config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :repositories, only: [:index]

  root to: 'repositories#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

require 'faraday'

class RepositoriesController < ApplicationController
  def index
    @response = request_api(search_params['query'], 1) if search_params['query'].present?
    if search_params['query'].present? && search_params['page'].present?
      @response = request_api(search_params['query'], search_params['page'])
    end
    if @response.present? && @response.status == 200
      @per_page = 30
      @selected_page = 1
      @total_result = JSON.parse(@response.body)['total_count']
      @total_pages = (@total_result.to_f / @per_page).ceil
      if search_params['page'].present? && search_params['page'].to_i <= @total_pages
        @selected_page = search_params['page']
      elsif search_params['page'].to_i > @total_pages
        @response = request_api(search_params['query'], 1)
      end
      @repositories = JSON.parse(@response.body)['items']
    else
      @total_result = 0
      @repositories = []
    end
  end

  private

  def search_params
    params.permit(:query,
                  :page)
  end

  def request_api(query, page)
    url = 'https://api.github.com/search/repositories'
    Faraday.get(url, { q: query, page: page })
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/repositories_helper.rb
# frozen_string_literal: true

module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PublicRepoSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/index.html.erb
<div class = "container">
  <h1>Public repositories</h1>
  <%= form_tag repositories_path, method: :get do %>
    <%= label_tag(:name, "Search a Repo:") %>
    <%= text_field_tag :query, params["query"] %>
    <%= submit_tag "Search", name: nil %>
    <% if @total_result > 0 %>
      <th><%= @total_result %> repo found</th>
      <% if @total_pages > 0 %>
        <th>-- <%= @total_pages %> page/pages found, select page</th>
        <%= select_tag :page, options_for_select(1..@total_pages, @selected_page), onchange: "this.form.submit();" %>
      <% end %>
    <% end %>
  <% end %>

  <table>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Owner</th>
      <th>User Image</th>
    </tr>
    <% @repositories.each do |item| %>
      <tr>
        <td><%= item['id'] %></td>
        <td><%= item['name'] %></td>
        <td><%= item['owner']['login'] %></td>
        <td><%= image_tag item['owner']['avatar_url'], size: "50x50" %></td>
      </tr>
    <% end %>
  </table>
</div>